name: .NET

on:
  push:
    branches: [ mrbrayan ]
  pull_request:
    branches: [ mrbrayan ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  ci_to_master: 
    runs-on: ubuntu-latest
    needs: [build]
    defaults:
      run:
        working-directory: ClientApp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      #- run: npm test
      - run: npm run build
